language: node_js
sudo: false

node_js:
  - "4"
  - "6"
  - "7"
  - "8"
  - "9"

after_success:
  - npm run coverage
  - npm i codecov
  - codecov -f coverage/coverage.json

notifications:
  email:
    on_success: never

cache:
  directories:
  - node_modules
