language: node_js
sudo: false

node_js:
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"

after_success:
  - npm run coverage
  - npm i codecov
  - codecov -f coverage/coverage.json

notifications:
  email: false

cache:
  directories:
  - node_modules
